cryptonews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.home, name="home"),
    path('prices', views.prices, name="prices"),
]

news/models.py
from django.db import models

# Create your models here.

news/views.py
import requests
import json

from django.shortcuts import render


def home(request):
    # Grab Crypto Price Data
    price_request = requests.get(
        "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,BCH,EOS,XLM,LTC,USDT,XMR,ADA,MIOTA&tsyms=USD")
    price = json.loads(price_request.content)

    # Grab Crypto News
    api_request = requests.get(
        "https://min-api.cryptocompare.com/data/v2/news/?lang=EN")
    api = json.loads(api_request.content)

    return render(request, 'home.html', {'api': api, 'price': price})


def prices(request):
    if request.method == 'POST':
        quote = request.POST['quote']
        quote = quote.upper()
        crypto_request = requests.get(
            "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=" + quote + "&tsyms=USD")
        crypto = json.loads(crypto_request.content)

        return render(request, 'prices.html', {'quote': quote, 'crypto': crypto})

    else:
        notfound = "Enter a crypto currency symbol into the form above..."
        return render(request, 'prices.html', {'notfound': notfound})

news/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Crypto News!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'news:home' %}">Crypto News Network</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:prices' %}">Lookup Prices</a>
                </li> 
            </ul>
            <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'news:prices' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Lookup Crypto" aria-label="Search" name="quote">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Lookup</button>
            </form>
        </div>
    </nav>
    <br />
    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

news/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">Welcome To Crypto News Network!</h1>
    <p class="lead">Your Source For Up To The Minute Crypto Currency and Blockhain News!</p>
</div>
<br />

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">24 High</th>
            <th scope="col">24 Low</th>
            <th scope="col">MarketCap</th>
        </tr>
    </thead>
    <tbody>
        {% for key, value in price.DISPLAY.items %}
        <tr>
            <th>{{ key }}</th>
            <td>{{ value.USD.PRICE }}</td>
            <td>{{ value.USD.HIGHDAY }}</td>
            <td>{{ value.USD.LOWDAY }}</td>
            <td>{{ value.USD.MKTCAP }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br /><br />

<div class="row">
    {% for x in api.Data %}
    <div class="col-sm">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{ x.imageurl }}" alt="{{ x.source }}">
            <div class="card-body">
                <h5 class="card-title">{{ x.title }}</h5>
                <p class="card-text">{{ x.body }}</p>
                <a href="{{ x.url }}" class="btn btn-secondary">Read More...</a>
            </div>
        </div>
        <br>
    </div>
    {% endfor %}
</div>

{% endblock %}

news/templates/prices.html
{% extends 'base.html' %}

{% block content %}

{% if notfound %}
    <div class="alert alert-primary" role="alert">
        {{ notfound }}
    </div>
{% else %}
    {% if crypto.Response %}
        <div class="alert alert-primary" role="alert">
            Sorry, {{ quote }} symbol doesn't exist. Please Try Again...
        </div>
    {% endif %}
    {% for key,value in crypto.DISPLAY.items %}
        <div class="jumbotron">
            <h1 class="display-4">{{ key }}</h1>
            <strong>Name</strong>: {{ key }} <br />
            <strong>Price</strong>: {{ value.USD.PRICE }} <br />
            <strong>Day High</strong>: {{ value.USD.HIGHDAY }} <br />
            <strong>Day Low</strong>: {{ value.USD.LOWDAY }} <br />
            <strong>Market Cap</strong>: {{ value.USD.MKTCAP }} <br />
        </div>
    {% endfor %}
{% endif %}
{% endblock %}